import { billing } from './billing.js';
import { authConfig, OWNER_CHATGPT_USER_ID, OWNER_GOOGLE_EMAIL } from './auth.js';
const ADMIN_HTML = '__ADMIN_HTML__';
const ZONE_ID = '19fc99ed5a9bc17308d434c3c7d959aa';
const ALLOWED_DAYS = new Set([7, 30]);

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'no-referrer',
    },
  });
}

function utcWindow(days, now = new Date()) {
  const today = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  return {
    start: new Date(today - (days - 1) * 86400000).toISOString().slice(0, 10),
    end: new Date(today + 86400000).toISOString().slice(0, 10),
  };
}

function analyticsQuery(start, end) {
  // start and end are generated by utcWindow, never supplied by the visitor.
  return `{viewer{zones(filter:{zoneTag:"${ZONE_ID}"}){daily:httpRequests1dGroups(limit:31,filter:{date_geq:"${start}",date_lt:"${end}"}){dimensions{date}sum{pageViews}uniq{uniques}}}}}`;
}

function normalizeDaily(groups, days, now = new Date()) {
  const { start } = utcWindow(days, now);
  const byDate = new Map();
  for (const row of groups) {
    const date = row?.dimensions?.date;
    const pageViews = row?.sum?.pageViews;
    const uniqueIps = row?.uniq?.uniques;
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isSafeInteger(pageViews) || pageViews < 0 || !Number.isSafeInteger(uniqueIps) || uniqueIps < 0) {
      throw new Error('Unexpected Cloudflare analytics response');
    }
    byDate.set(date, { date, pageViews, uniqueIps });
  }
  const dates = [];
  const first = Date.parse(`${start}T00:00:00Z`);
  for (let i = 0; i < days; i++) {
    const date = new Date(first + i * 86400000).toISOString().slice(0, 10);
    dates.push(byDate.get(date) ?? { date, pageViews: 0, uniqueIps: 0 });
  }
  return dates;
}

async function analytics(request, env) {
  if (request.method !== 'GET') return json({ error: 'Method not allowed' }, 405);
  const days = Number(new URL(request.url).searchParams.get('days') || 7);
  if (!ALLOWED_DAYS.has(days)) return json({ error: 'Choose 7 or 30 days' }, 400);
  if (!env.CLOUDFLARE_ANALYTICS_TOKEN) return json({ error: 'Cloudflare Analytics is not connected yet' }, 503);
  const window = utcWindow(days);
  let response;
  try {
    response = await (env.UPSTREAM_FETCH || fetch)('https://api.cloudflare.com/client/v4/graphql', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.CLOUDFLARE_ANALYTICS_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query: analyticsQuery(window.start, window.end), variables: {} }),
      signal: AbortSignal.timeout(10000),
    });
  } catch {
    return json({ error: 'Cloudflare Analytics is temporarily unavailable' }, 502);
  }
  if (!response.ok) return json({ error: 'Cloudflare rejected the analytics request. Check the token and its Account Analytics: Read permission.' }, 502);
  let payload;
  try { payload = await response.json(); } catch { return json({ error: 'Cloudflare returned an unreadable response' }, 502); }
  if (payload.errors?.length) return json({ error: 'Cloudflare could not return daily traffic for this zone or date range' }, 502);
  const groups = payload.data?.viewer?.zones?.[0]?.daily;
  if (!Array.isArray(groups)) return json({ error: 'Cloudflare returned no zone analytics data' }, 502);
  let series;
  try { series = normalizeDaily(groups, days); } catch { return json({ error: 'Cloudflare returned unexpected traffic values' }, 502); }
  return json({
    source: 'Cloudflare zone traffic',
    domain: 'retirementforecast.us',
    days,
    start: window.start,
    endExclusive: window.end,
    series,
    pageViews: series.reduce((sum, row) => sum + row.pageViews, 0),
    peakDailyUniqueIps: Math.max(0, ...series.map(row => row.uniqueIps)),
  });
}

function owner(request) {
  const userId = request.headers.get('oai-authenticated-user-id');
  if (!userId) return false;
  const email = request.headers.get('oai-authenticated-user-email')?.trim().toLowerCase();
  return userId === OWNER_CHATGPT_USER_ID || email === OWNER_GOOGLE_EMAIL;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === '/api/auth/config') return authConfig(request, env);
    if (url.pathname.startsWith('/api/billing/')) return billing(request, env, url.pathname, owner(request));
    if (url.pathname === '/api/admin/traffic') {
      if (!owner(request)) return json({ error: 'Admin access required' }, 403);
      return analytics(request, env);
    }
    if (url.pathname === '/admin' || url.pathname === '/admin/' || url.pathname === '/admin.html') {
      if (!owner(request)) {
        if (request.headers.get('oai-authenticated-user-id')) return new Response('Admin access required', { status: 403, headers: { 'Cache-Control': 'no-store' } });
        return Response.redirect(new URL('/signin-with-chatgpt?return_to=%2Fadmin', url), 302);
      }
      const headers = new Headers({ 'Content-Type': 'text/html; charset=utf-8' });
      headers.set('Cache-Control', 'no-store');
      headers.set('X-Robots-Tag', 'noindex, nofollow');
      headers.set('Referrer-Policy', 'no-referrer');
      headers.set('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
      return new Response(ADMIN_HTML, { status: 200, headers });
    }
    return env.ASSETS.fetch(request);
  },
};

export { analyticsQuery, normalizeDaily, utcWindow };
